import {useEffect,useMemo,useState} from 'react';
import curriculum from './curriculum.json';
import vessels from './vessels.json';
import {getDetailedCatalog} from './detailed-catalog';
import './study.css';
type Props={onLocate:(id:string,name:string)=>void;period:number;initialTab?:'topics'|'vessels'|'quiz';modelVariant?:'male'|'female'};
type CatalogEntry={id:string;name:string;system:string;objectCount:number;sourceId:string;aliases?:string[]};
export default function StudyPanel({onLocate,period,initialTab='topics',modelVariant='male'}:Props){
 const [tab,setTab]=useState(initialTab),[query,setQuery]=useState(''),[group,setGroup]=useState('Todos'),[topicId,setTopicId]=useState(curriculum.modules[0].id),[vesselId,setVesselId]=useState('carotida-externa'),[answer,setAnswer]=useState<number|null>(null),[show,setShow]=useState(false);
 const [catalog,setCatalog]=useState<CatalogEntry[]>([]),[catalogError,setCatalogError]=useState(false);
 const [done,setDone]=useState<string[]>(()=>{try{const d=JSON.parse(localStorage.getItem('mapa-mastery')||'[]');return Array.isArray(d)?d.filter(x=>typeof x==='string'):[]}catch{return[]}});
 useEffect(()=>{setTab(initialTab)},[initialTab]);
 const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const normalizeStructure=(s:string)=>normalize(s).replace(/_/g,'-');
 useEffect(()=>{let disposed=false;setCatalog([]);setCatalogError(false);getDetailedCatalog(modelVariant).then(entries=>{if(!disposed)setCatalog(entries as CatalogEntry[])}).catch(()=>{if(!disposed){setCatalogError(true)}});return()=>{disposed=true}},[modelVariant]);
 const topic=curriculum.modules.find(m=>m.id===topicId)!;const vessel=vessels.find(v=>v.id===vesselId) ?? vessels[0];
 const topics=useMemo(()=>curriculum.modules.filter(m=>(group==='Todos'||m.group===group)&&normalize(m.title+' '+m.points.join(' ')).includes(normalize(query))),[group,query]);
 useEffect(()=>{if(topics.length&&!topics.some(m=>m.id===topicId)){setTopicId(topics[0].id);setAnswer(null);setShow(false)}},[topics,topicId]);
 const matches=useMemo(()=>{const key=normalizeStructure(topic.structure);return catalog.filter(c=>[c.id,c.sourceId,...(c.aliases??[])].some(value=>normalizeStructure(value).includes(key)))},[catalog,topic.structure]);
 const visibleVessels=useMemo(()=>vessels.filter(v=>normalize(v.name+' '+v.territory).includes(normalize(query))),[query]);
 useEffect(()=>{if(visibleVessels.length&&!visibleVessels.some(v=>v.id===vesselId))setVesselId(visibleVessels[0].id)},[visibleVessels,vesselId]);
 const vesselMatches=useMemo(()=>vessel.geometryIds.map(id=>catalog.find(c=>c.sourceId===id)).filter((entry):entry is CatalogEntry=>Boolean(entry)),[catalog,vessel.geometryIds]);
 const choose=(id:string)=>{setTopicId(id);setAnswer(null);setShow(false)};
 const master=()=>{const next=done.includes(topicId)?done.filter(x=>x!==topicId):[...done,topicId];setDone(next);try{localStorage.setItem('mapa-mastery',JSON.stringify(next))}catch{}};
 const lineage=[];let cursor= vessel;while(cursor){lineage.unshift(cursor);const parent=vessels.find(v=>v.id===cursor.parent);if(!parent)break;cursor=parent}
 return <section className="study-panel"><header><small>SEUS MATERIAIS · 2º PERÍODO</small><h2>Do conteúdo à identificação</h2><p>{curriculum.modules.length} tópicos e {curriculum.modules.length} questões autorais orientados por seis materiais. Sínteses educacionais; não representam toda a formação médica.</p></header>
 <div className="panel-tabs" role="tablist" aria-label="Trilhas de estudo">{[['topics','Aprender'],['vessels',`${vessels.length} vasos`],['quiz','Praticar']].map(([id,label])=><button role="tab" aria-selected={tab===id} className={tab===id?'active':''} key={id} onClick={()=>setTab(id as typeof tab)}>{label}</button>)}</div>
 <label className="study-search">Buscar <input aria-label="Buscar conteúdo de estudo" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Carótida, duodeno, vias ópticas…"/></label>
 {tab==='vessels'?<><p className="representation-note">Árvore vascular didática para o modelo {modelVariant==='female'?'feminino':'masculino'}. A disponibilidade de cada vaso no atlas aparece abaixo; variantes de origem e território existem.</p><select aria-label="Selecionar vaso" value={visibleVessels.some(v=>v.id===vesselId)?vesselId:''} onChange={e=>setVesselId(e.target.value)}>{visibleVessels.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select><div className="vascular-path" aria-label="Caminho de ramificação">{lineage.map(v=><button key={v.id} className={v.id===vesselId?'current':''} onClick={()=>setVesselId(v.id)}>{v.name}<span>↓</span></button>)}</div><h3>{vessel.name}</h3><p>{vessel.territory}</p><small>Padrão usual; a árvore simplifica anastomoses.</small><h4>Seguir para um ramo</h4><div className="branch-list">{vessels.filter(v=>v.parent===vesselId).map(v=><button key={v.id} onClick={()=>setVesselId(v.id)}>{v.name} →</button>)}{!vessels.some(v=>v.parent===vesselId)&&<p>Fim deste ramo no roteiro atual.</p>}</div><h4>Disponível neste modelo</h4>{vesselMatches.length?<div className="branch-list">{vesselMatches.map(m=><button key={m.sourceId} onClick={()=>onLocate(m.id,m.name)}>{m.name} ↗</button>)}</div>:<p>Este vaso está disponível como roteiro didático, mas não possui malha individual neste modelo.</p>}<a href="https://openstax.org/books/anatomy-and-physiology-2e/pages/20-5-circulatory-pathways" target="_blank" rel="noreferrer">Referência de circulação ↗</a><details><summary>Correções importantes das apostilas</summary><p>A oftálmica habitualmente nasce da carótida interna. A cerebral média não integra o anel clássico de Willis. A transversa da face normalmente é ramo da temporal superficial. Palatinas maior e menores derivam da palatina descendente.</p><a href="https://www.ncbi.nlm.nih.gov/books/NBK482317/" target="_blank" rel="noreferrer">Origem da oftálmica · NCBI ↗</a></details></>:<>
 <div className="study-filters"><select aria-label="Sistema de estudo" value={group} onChange={e=>setGroup(e.target.value)}>{['Todos',...new Set(curriculum.modules.map(m=>m.group))].map(g=><option key={g}>{g}</option>)}</select><select aria-label="Tópico de estudo" value={topicId} onChange={e=>choose(e.target.value)}>{topics.map(m=><option key={m.id} value={m.id}>{done.includes(m.id)?'✓ ':''}{m.title}</option>)}</select></div>{topics.length===0&&<p role="status">Nenhum tópico corresponde à busca.</p>}
 <div className="mastery"><progress value={done.length} max={curriculum.modules.length}/><small>{done.length}/{curriculum.modules.length} tópicos marcados como estudados</small></div><h3>{topic.title}</h3><span className="level-badge">{period<=2?'Identificar e nomear':period<=4?'Relacionar estrutura e função':'Integrar topografia e clínica'}</span>
 {tab==='topics'?<><ol className="study-objectives">{topic.points.map((p,i)=><li key={p}><strong>{['Reconheça','Relacione','Diferencie'][i]}</strong><p>{p}</p></li>)}</ol><h4>Conexão clínica</h4><p>{topic.clinic}</p><h4>Localizar no modelo 3D</h4>{matches.length?<div className="branch-list">{matches.slice(0,12).map(m=><button key={m.id} onClick={()=>onLocate(m.id,m.name)}>{m.name} ↗</button>)}</div>:<p>{catalogError?'Não foi possível carregar a disponibilidade do modelo.':'Esta estrutura não está individualizada neste modelo. O conteúdo permanece disponível para estudo.'}</p>}<button className="study-primary" onClick={()=>setTab('quiz')}>Testar meu conhecimento →</button></>:<><p className="question-origin">Questão autoral baseada nos temas dos materiais; não é reprodução de um gabarito oficial.</p><h4>{topic.question}</h4><div className="study-answers">{topic.options.map((option,i)=><button key={option} aria-pressed={answer===i} className={answer===i?'selected':''} onClick={()=>{setAnswer(i);setShow(false)}}>{String.fromCharCode(65+i)}. {option}</button>)}</div><button className="study-primary" disabled={answer===null} onClick={()=>setShow(true)}>Conferir e entender</button>{show&&<div className="answer-review" role="status"><strong>{answer===topic.correct?'Correto.':'Vamos revisar.'} Resposta: {topic.options[topic.correct]}.</strong><p>{topic.points.join(' ')}</p><p>{topic.clinic}</p><button onClick={()=>setTab('topics')}>Rever anatomia</button></div>}</>}
 <div className="study-actions"><button onClick={master}>{done.includes(topicId)?'✓ Estudado — desfazer':'Marcar como estudado'}</button><button onClick={()=>choose(curriculum.modules[(curriculum.modules.indexOf(topic)+1)%curriculum.modules.length].id)}>Próximo tópico →</button></div><details><summary>Material de origem e referência</summary><p>{curriculum.sources.find(s=>s.id===topic.source)?.title} · páginas {topic.pages}.</p><a href={topic.reference} target="_blank" rel="noreferrer">Referência complementar ↗</a><p>Os PDFs pessoais não são publicados. Alternativas marcadas nas provas não foram presumidas corretas.</p></details></>}
 </section>
}
